import "@/styles/globals.css";
import { ColorSchemeScript } from "@mantine/core";
import "@mantine/core/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/notifications/styles.css";

import { Inter } from "next/font/google";

import MainLayout from "@/layouts/MainLayout";
import { MantineProvider } from "@/providers/MantineProvider";
import { TRPCReactProvider } from "@/trpc/react";
import { Notifications } from "@mantine/notifications";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Gym Buddy",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />

        <ColorSchemeScript />
      </head>
      <body className={`font-sans ${inter.variable}`}>
        <MantineProvider>
          <TRPCReactProvider>
            <MainLayout>{children}</MainLayout>
          </TRPCReactProvider>
          <Notifications />
        </MantineProvider>
      </body>
    </html>
  );
}
